# serverless.yml
service:
  name: GameRecommenderBot


# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-kms-secrets
  - serverless-dynamodb-local
  - serverless-offline-scheduler
  - serverless-offline

custom:
  kmsSecrets: ${file(kms-secrets.${opt:stage, self:provider.stage}.${opt:region, self:provider.region}.yml)}
  serverless-offline:
    port: 4000
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      noStart: true

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 320 # optional, in MB, default is 1024
  timeout: 15 # optional, in seconds, default is 6
  region: us-west-2
  apiKeys:
    - discordRelayApiKey
  environment:
    SECRETS: ${self:custom.kmsSecrets.secrets.SECRETS}
    STAGE: ${opt:stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-west-2:*:*"
    - Effect: Allow
      Action:
        - KMS:Decrypt
      Resource: ${self:custom.kmsSecrets.keyArn}

resources:
  Resources:
    PostedSteamAnnouncements:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: GRB.PostedSteamAnnouncements
        AttributeDefinitions:
          - AttributeName: PostId
            AttributeType: S
        KeySchema:
          - AttributeName: PostId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  steamAnnouncements:
    handler: src/main.steamAnnouncements
    name: ${self:provider.stage}-SteamAnnouncements
    description: Check and post relevant steam announcements to Reddit
    events:
      - schedule: rate(15 minutes)
  receiveMessages:
    handler: src/main.receiveMessages
    name: ${self:provider.stage}-ReceiveMessage
    description: Receive message from the Discord Channel.
    events:
      - http:
          private: true
          path: message/new
          method: get
          request:
            parameters:
              querystrings:
                message: true
